Fix typos in docs, comments and variables
manifoldco/heighliner pull request #120
Opened 2018-10-11 13:57 UTC by alexandear

2018-10-11 13:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/manifoldco/heighliner?pullRequest=120) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/manifoldco/heighliner?pullRequest=120) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/manifoldco/heighliner?pullRequest=120) it.</sub>

2018-10-11 17:22 UTC, domenicrosati submitted a review, later dismissed
ship it

2018-10-11 17:27 UTC, domenicrosati commented on cmd/heighliner/zz_generated_data.go
> +	canonicalName := strings.Replace(name, "\\", "/", -1)
we shouldn't change this file because its generated

2018-10-11 17:28 UTC, domenicrosati requested changes
Thanks for submitting a PR! awesome. Only one small request about the generated file

2018-10-12 08:37 UTC, alexandear commented
@domenicrosati fixed

2018-10-12 09:18 UTC, jelmersnoeck submitted a review, later dismissed

2018-10-12 12:52 UTC, domenicrosati submitted a review, later dismissed

2018-12-14 13:42 UTC, jelmersnoeck commented
Hey @alexandear ! Thanks for this. Apologies for the delay.

We've fixed the Travis CI parts in master, would you be able to update your branch?

2018-12-14 13:59 UTC, alexandear commented
Update branch.

2018-12-14 14:11 UTC, jelmersnoeck approved these changes

2018-12-14 14:11 UTC, merged